name: lighthouse-ci

on:
  push:
    branches:
      - feature/lighthouse-ci

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install && npm install -g @lhci/cli@0.14.x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start Docker containers
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml --env-file test.env --profile postgres up -d --build

      - run: lhci autorun

      - name: Stop Docker containers
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml --env-file test.env --profile postgres down
